spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/electro_store
    username: postgres
    password: 511007
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
